# Generated by Django 4.0.4 on 2022-06-11 18:32

from django.db import migrations, models
import django_tiptap2.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_tiptap2.fields.TipTapTextField()),
                ('somethingMore', django_tiptap2.fields.TipTapTextField(null=True)),
            ],
        ),
    ]
